import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../../src/components/Header"
import ToggleBtn from "../../src/components/ToggleBtn"
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "My Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-[#090D1F] text-black dark:text-white lg:w-[80%] mx-auto`}>
        <Header />
        <ToggleBtn />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
